# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=100)),
                ('btutor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('ugender', models.BooleanField()),
                ('uage', models.IntegerField()),
                ('ucode', models.CharField(max_length=50)),
                ('uemail', models.EmailField(max_length=254)),
                ('ujob', models.CharField(max_length=10)),
                ('ulbook', models.BooleanField()),
            ],
        ),
    ]
