# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0005_user_ulbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=30, verbose_name='笔记标题')),
                ('aauthor', models.CharField(max_length=30, verbose_name='笔记作者')),
                ('abookname', models.CharField(max_length=30, verbose_name='书籍名称')),
                ('awriter', models.CharField(max_length=30, verbose_name='书籍作者')),
                ('acontent', models.TextField(max_length=10000, verbose_name='笔记正文')),
            ],
        ),
    ]
