# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0006_auto_20171121_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='acontent',
            field=models.TextField(max_length=1000, verbose_name='笔记正文'),
        ),
    ]
