# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='btitle',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='book',
            name='btutor',
            field=models.CharField(max_length=50, verbose_name='作者'),
        ),
    ]
