# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_auto_20171115_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ugender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ulbook',
        ),
    ]
