# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0004_user_ugender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ulbook',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
