# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0010_auto_20171124_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbookname', models.CharField(max_length=30, verbose_name='书籍名称')),
                ('bwriter', models.CharField(max_length=30, verbose_name='书籍作者')),
                ('barticlenumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='uarticlenumber',
            field=models.IntegerField(default=0),
        ),
    ]
