# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0011_auto_20171125_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likenumber',
            field=models.IntegerField(default=0),
        ),
    ]
