# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0012_auto_20171128_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starusername', models.CharField(max_length=50, verbose_name='收藏用户')),
                ('staruserauthor', models.CharField(max_length=50, verbose_name='我收藏的用户')),
            ],
        ),
    ]
